# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20170211_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default='pics/no-img.jpg', upload_to='pics/'),
        ),
    ]
