# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_post_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default='uploaded_pics/no-img.jpg', upload_to='uploaded_pics/'),
        ),
    ]
