# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20170211_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default='/uploads/pics/no-img.jpg', upload_to='/uploads/pics/'),
        ),
    ]
