# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_auto_20170211_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_topic',
            field=models.CharField(choices=[('m', 'Maths'), ('s', 'Software')], default='m', max_length=10),
        ),
    ]
